import:
  - ~/.config/alacritty/dracula.yml
background_opacity: 0.9

font:
  normal:
    family: "Cascadia Code"
    style: Regular
  bold:
    family: "Cascadia Code"
    style: Bold
  italic:
    family: "Cascadia Code"
    style: Italic
  bold_italic:
    family: "Cascadia Code"
    style: Bold Italic

  # Point size
  size: 8.0

  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

window:
  padding:
    x: 2
    y: 2

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 10

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  # I comment this out, because I am not sure I need it and it might fuck things up
  #save_to_clipboard: true

live_config_reload: true

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Equals, mods: Control, action: IncreaseFontSize }
#shell:
#program: /usr/bin/tmux
#args:
#- attach
