config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  workdir: ~/.config/dotfiles
dotfiles:
    d_i3:
        dst: ~/.config/i3
        src: config/i3
    d_shell:
        dst: ~/.config/shell
        src: config/shell
    d_fish:
        dst: ~/.config/fish
        src: config/fish
    f_tmux:
        dst: ~/.tmux.conf
        src: config/tmux.conf

profiles:
    all:
        #Common profile for all devices
        dotfiles:
        - d_shell
    linux:
        # dot files for Linux install
        dotfiles:
        - d_i3
        - d_fish
        - f_tmux
