config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  workdir: ~/.config/dotfiles
dotfiles:
    d_i3:
        dst: ~/.config/i3
        src: config/i3
    d_shell:
        dst: ~/.config/shell
        src: config/shell
profiles:
    all:
        #Common profile for all devices
        dotfiles:
        - d_shell
    linux:
        # dot files for Linux install
        dotfiles:
        - d_i3
    tina:
        dotfiles:
        - d_shell
