#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
HOST_SPECIFIC_CONFIG_FILE="${HOSTNAME}.conf.yml"

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

if [ -f  "$HOST_SPECIFIC_CONFIG_FILE" ]
then
    echo "Specification configuration file ${HOST_SPECIFIC_CONFIG_FILE} found !"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${HOST_SPECIFIC_CONFIG_FILE}" "${@}"
fi
